# Generated by Django 3.1.3 on 2021-04-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0004_auto_20210104_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_with_sites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('themes', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('sites', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('history', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
    ]
